[project]
name = "backend"
version = "0.1.0"
description = "Backend for knowledge engine"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.123.0",
    "uvicorn>=0.38.0",
]
